### ISSUE TITLE
standalone hazlecast cluster ?

### ISSUE THREAD

**Issue by cameronbraid** [zeebe-io/zeebe-hazelcast-exporter#63]
Anyone implemented a docker container that runs a standalone hazlecast cluster suitable for pointing multiple hazlecast exporters to ?

**Comment by saig0** [comment]
There is an official Hazelcast image that you can use: `hazelcast/hazelcast:4.0.1`

Example from the docker-compose file:
```
  hazelcast:
    container_name: hazelcast
    image: hazelcast/hazelcast:4.0.1
    ports:
      - "5701:5701"
    environment:
      - JAVA_OPTS="-Dhazelcast.local.publicAddress=hazelcast:5701"
    networks:
      - zeebe_network
```

Is this what you're looking for?
